name: opera_calval_rtc
channels:
  - conda-forge
dependencies:
  - python=3.11 # for papermill, which requires 5yr old https://anaconda.org/conda-forge/ansiwrap
  - asf_search
  - branca
  - boto3
  - dask
  - distributed
  - earthaccess>=0.9.0
  - folium
  - gdal  
  - geopandas
  - ipyfilechooser
  - ipywidgets
  - ipympl
  - isce3
  - jupyter
  - jupyterlab~=4.0
  - jupyterlab_widgets~=3.0
  - lmfit
  - matplotlib<3.7.0
  - mgrs
  - numpy 
  - opensarlab_lib
  - pandas
  - pandoc
  - papermill
  - plotly
  - pyproj
  - pysolid
  - rasterio
  - rioxarray
  - scikit-image
  - scipy
  - pip
  - weasyprint
  - wget
  - pip:
    - shapely
